--------------------------------------------------------
--  Fichier créé - mardi-mai-04-2021   
--------------------------------------------------------
DROP TABLE "SOFIENE"."ALARME";
DROP TABLE "SOFIENE"."ARTICLES";
DROP TABLE "SOFIENE"."EMISSIONS";
DROP TABLE "SOFIENE"."EMPLOYE";
DROP TABLE "SOFIENE"."EVENEMENTS";
DROP TABLE "SOFIENE"."FONCTION";
DROP TABLE "SOFIENE"."HISTORIQUE";
DROP TABLE "SOFIENE"."MISSION";
DROP TABLE "SOFIENE"."PARTICIPANTS";
DROP TABLE "SOFIENE"."JOURNALISTE";
--------------------------------------------------------
--  DDL for Table ALARME
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."ALARME" 
   (	"DATEA" VARCHAR2(20 BYTE), 
	"HEUREA" VARCHAR2(20 BYTE), 
	"NOM_ALARME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ARTICLES
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."ARTICLES" 
   (	"NOM_AUTEUR" VARCHAR2(20 BYTE), 
	"NOM_ARTICLE" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMISSIONS
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."EMISSIONS" 
   (	"NOM_EMISSION" VARCHAR2(20 BYTE), 
	"NOM_PRESENTATEUR" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."EMPLOYE" 
   (	"NOMPRENOM" VARCHAR2(50 BYTE), 
	"ID" NUMBER(8,0), 
	"N_CIN" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"N_TEL" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"LOGIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENTS
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."EVENEMENTS" 
   (	"ID" NUMBER, 
	"CAPACITE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FONCTION
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."FONCTION" 
   (	"ID" NUMBER(8,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"CARACT" VARCHAR2(100 BYTE), 
	"NBHEURE" NUMBER(2,0), 
	"DIPLOME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."HISTORIQUE" 
   (	"TYPE_OPERATION" VARCHAR2(20 BYTE), 
	"ENTITE" VARCHAR2(20 BYTE), 
	"DATEO" VARCHAR2(20 BYTE), 
	"HEUREO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSION
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."MISSION" 
   (	"ID" NUMBER(30,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"LOCALISATION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."PARTICIPANTS" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOURNALISTE
--------------------------------------------------------

  CREATE TABLE "SOFIENE"."JOURNALISTE" 
   (	"ID" NUMBER(30,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(40 BYTE), 
	"SPECIALITE" VARCHAR2(20 BYTE), 
	"NUM" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SOFIENE.ALARME
SET DEFINE OFF;
Insert into SOFIENE.ALARME (DATEA,HEUREA,NOM_ALARME) values ('01/01/2000','12:00 AM','pause');
Insert into SOFIENE.ALARME (DATEA,HEUREA,NOM_ALARME) values ('03/05/2020','12:00 AM','pause');
REM INSERTING into SOFIENE.ARTICLES
SET DEFINE OFF;
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('eaeae','aeaeaea','aeaeaeae','eaeaea');
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('eaeaee','eaeaeae','azazaaz','aeaeaea');
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('eaeea','aeae','bbbbb','aeea');
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('eaeaa','aeaeaa','erreaea','aaeaeaa');
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('eaeaeea','eaeaeae','babababa','a');
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('eaeaeae','eaeeaea','1234','eaeeae');
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('aeeaea','eaeae','eaeaea','aaeaeaeea');
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('eaeaeae','eaeaaea','eaeaaaaa','raea');
Insert into SOFIENE.ARTICLES (NOM_AUTEUR,NOM_ARTICLE,ID,TYPE) values ('eaeaeea','eaeaea','aeaeae','aaaaa');
REM INSERTING into SOFIENE.EMISSIONS
SET DEFINE OFF;
Insert into SOFIENE.EMISSIONS (NOM_EMISSION,NOM_PRESENTATEUR,ID) values ('aeeaea','aeea','1234');
Insert into SOFIENE.EMISSIONS (NOM_EMISSION,NOM_PRESENTATEUR,ID) values ('eaeaea','aeeaeae','aeaeaea');
Insert into SOFIENE.EMISSIONS (NOM_EMISSION,NOM_PRESENTATEUR,ID) values ('aeae','eaea','eaeae');
Insert into SOFIENE.EMISSIONS (NOM_EMISSION,NOM_PRESENTATEUR,ID) values ('12345','eaeaeae','aeaeaeae');
Insert into SOFIENE.EMISSIONS (NOM_EMISSION,NOM_PRESENTATEUR,ID) values ('AEEAEAEAEAE','EAEAEAAEEAEEAE','12345');
Insert into SOFIENE.EMISSIONS (NOM_EMISSION,NOM_PRESENTATEUR,ID) values ('eaeae','eaeaeae','123456');
Insert into SOFIENE.EMISSIONS (NOM_EMISSION,NOM_PRESENTATEUR,ID) values ('aeeae','eaea','aeaea');
REM INSERTING into SOFIENE.EMPLOYE
SET DEFINE OFF;
REM INSERTING into SOFIENE.EVENEMENTS
SET DEFINE OFF;
REM INSERTING into SOFIENE.FONCTION
SET DEFINE OFF;
Insert into SOFIENE.FONCTION (ID,NOM,CARACT,NBHEURE,DIPLOME) values (123,'saasa','eaeaea',12,'rien');
REM INSERTING into SOFIENE.HISTORIQUE
SET DEFINE OFF;
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','01/05/2021','15:30:28');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','01/05/2021','15:32:42');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','01/05/2021','15:32:57');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','01/05/2021','15:33:39');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Articles','01/05/2021','15:36:49');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','01/05/2021','15:48:02');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','01/05/2021','15:53:01');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Articles','01/05/2021','15:53:50');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Articles','01/05/2021','15:53:56');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Articles','01/05/2021','15:54:01');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Articles','01/05/2021','15:54:05');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Articles','01/05/2021','15:54:09');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Articles','01/05/2021','15:54:19');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','01/05/2021','15:54:37');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('modification','Articles','01/05/2021','15:57:16');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Emissionss','03/05/2021','00:18:45');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','emission','03/05/2021','00:18:57');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Modification','Emissions','03/05/2021','00:19:11');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','03/05/2021','00:19:35');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('modification','Articles','03/05/2021','00:19:48');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Suppression','Articles','03/05/2021','00:19:53');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','emission','03/05/2021','00:23:49');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Modification','Emissions','03/05/2021','00:24:04');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','03/05/2021','00:24:20');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','emission','03/05/2021','00:25:07');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('modification','Articles','03/05/2021','00:25:16');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','Articles','03/05/2021','00:25:29');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','emission','03/05/2021','00:25:35');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Modification','Emissions','03/05/2021','00:26:09');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','emission','03/05/2021','00:26:37');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','emission','03/05/2021','00:26:45');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Modification','Emissions','03/05/2021','00:26:54');
Insert into SOFIENE.HISTORIQUE (TYPE_OPERATION,ENTITE,DATEO,HEUREO) values ('Ajout','emission','03/05/2021','00:36:48');
REM INSERTING into SOFIENE.MISSION
SET DEFINE OFF;
REM INSERTING into SOFIENE.PARTICIPANTS
SET DEFINE OFF;
REM INSERTING into SOFIENE.JOURNALISTE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ARTICLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFIENE"."ARTICLES_PK" ON "SOFIENE"."ARTICLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMISSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFIENE"."EMISSIONS_PK" ON "SOFIENE"."EMISSIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFIENE"."EMPLOYE_PK" ON "SOFIENE"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFIENE"."EVENEMENTS_PK" ON "SOFIENE"."EVENEMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FONCTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFIENE"."FONCTION_PK" ON "SOFIENE"."FONCTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MISSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFIENE"."MISSION_PK" ON "SOFIENE"."MISSION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTICIPANTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFIENE"."PARTICIPANTS_PK" ON "SOFIENE"."PARTICIPANTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JOURNALISTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOFIENE"."JOURNALISTE_PK" ON "SOFIENE"."JOURNALISTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ARTICLES
--------------------------------------------------------

  ALTER TABLE "SOFIENE"."ARTICLES" ADD CONSTRAINT "ARTICLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOFIENE"."ARTICLES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMISSIONS
--------------------------------------------------------

  ALTER TABLE "SOFIENE"."EMISSIONS" ADD CONSTRAINT "EMISSIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOFIENE"."EMISSIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SOFIENE"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOFIENE"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENEMENTS
--------------------------------------------------------

  ALTER TABLE "SOFIENE"."EVENEMENTS" ADD CONSTRAINT "EVENEMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOFIENE"."EVENEMENTS" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."EVENEMENTS" MODIFY ("DATE_FIN" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."EVENEMENTS" MODIFY ("DATE_DEBUT" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."EVENEMENTS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."EVENEMENTS" MODIFY ("CAPACITE" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."EVENEMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FONCTION
--------------------------------------------------------

  ALTER TABLE "SOFIENE"."FONCTION" ADD CONSTRAINT "FONCTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOFIENE"."FONCTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MISSION
--------------------------------------------------------

  ALTER TABLE "SOFIENE"."MISSION" ADD CONSTRAINT "MISSION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOFIENE"."MISSION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "SOFIENE"."PARTICIPANTS" ADD CONSTRAINT "PARTICIPANTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOFIENE"."PARTICIPANTS" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."PARTICIPANTS" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."PARTICIPANTS" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."PARTICIPANTS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SOFIENE"."PARTICIPANTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOURNALISTE
--------------------------------------------------------

  ALTER TABLE "SOFIENE"."JOURNALISTE" ADD CONSTRAINT "JOURNALISTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SOFIENE"."JOURNALISTE" MODIFY ("ID" NOT NULL ENABLE);
